# Generated by Django 4.0.2 on 2022-03-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, max_length=255)),
                ("image_path", models.URLField(blank=True, max_length=255)),
                ("name", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
