/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/core/products/": {
    get: operations["listProducts"];
  };
  "/api/v1/core/products/{id}/": {
    get: operations["retrieveProduct"];
    put: operations["updateProduct"];
    delete: operations["destroyProduct"];
    patch: operations["partialUpdateProduct"];
  };
}

export interface components {
  schemas: {
    Product: {
      url?: string;
      name?: string;
      description?: string;
      /** Format: binary */
      image_path: string;
      barcode: string;
    };
  };
}

export interface operations {
  listProducts: {
    parameters: {
      query: {
        /** Number of results to return per page. */
        limit?: number;
        /** The initial index from which to return the results. */
        offset?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            /** @example 123 */
            count?: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results?: components["schemas"]["Product"][];
          };
        };
      };
    };
  };
  retrieveProduct: {
    parameters: {
      path: {
        /** A unique integer value identifying this product. */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
    };
  };
  updateProduct: {
    parameters: {
      path: {
        /** A unique integer value identifying this product. */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Product"];
        "application/x-www-form-urlencoded": components["schemas"]["Product"];
        "multipart/form-data": components["schemas"]["Product"];
      };
    };
  };
  destroyProduct: {
    parameters: {
      path: {
        /** A unique integer value identifying this product. */
        id: string;
      };
    };
    responses: {
      204: never;
    };
  };
  partialUpdateProduct: {
    parameters: {
      path: {
        /** A unique integer value identifying this product. */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Product"];
        "application/x-www-form-urlencoded": components["schemas"]["Product"];
        "multipart/form-data": components["schemas"]["Product"];
      };
    };
  };
}

export interface external {}
